Repository cheshire-cat-ai/core, pull requests merged in 2024-11, with the labels that each got.

#964 New "*endpoint" decorators for custom endpoint creations
  core/cat/looking_glass/cheshire_cat.py
  core/cat/mad_hatter/decorators/__init__.py
  core/cat/mad_hatter/decorators/endpoint.py
  core/cat/mad_hatter/mad_hatter.py
  core/cat/mad_hatter/plugin.py
  core/cat/routes/plugins.py
  core/cat/startup.py
  core/tests/conftest.py
  core/tests/mad_hatter/test_endpoints.py
  core/tests/mad_hatter/test_plugin.py
  core/tests/mocks/mock_plugin/mock_endpoint.py
Labels: enhancement, endpoints

#970 Forms model getter
  core/cat/experimental/form/cat_form.py
Labels: enhancement

#966 chore: plugin compatibility infos
  core/cat/mad_hatter/plugin.py
Labels: enhancement

#968 refactor(v2)!: update langchain
  core/cat/factory/custom_llm.py
  core/cat/looking_glass/cheshire_cat.py
  core/pyproject.toml
Labels: V2
